name: Build Windows EXE

on: 
  push:
    branches: [ "main" ]  # Se déclenche quand vous poussez sur la branche main

jobs:
  build:
    runs-on: windows-latest  # On utilise un serveur Windows

    steps:
      - name: Recupérer le code
        uses: actions/checkout@v4  # 'uses' est obligatoire ici

      - name: Installer Python
        uses: actions/setup-python@v5  # 'uses' est obligatoire ici
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller
        # 'run' est obligatoire pour lancer des commandes shell

      - name: Créer l'executable
        run: pyinstaller --onefile --noconsole --add-data "assets;assets" christmasInvader.py
        # Remplacez 'mon_jeu.py' par le nom de votre fichier principal

      - name: Sauvegarder l'EXE 
        uses: actions/upload-artifact@v4
        with:
          name: christmasInvaders
          path: dist/*.exe

      - name: Créer une Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}