name: Build Christmas and Space Invaders

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch: # Permet de lancer le build manuellement si besoin

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        # On définit les deux fichiers source ici
        file: [christmasInvader.py, SpaceInvader.py]

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller

      - name: Créer l'executable
        # --add-data "assets/*;." met les images à la racine de l'EXE 
        # pour correspondre à votre erreur précédente
        run: pyinstaller --onefile --noconsole --add-data "assets;assets" --name "${{ matrix.file == 'christmasInvader.py' && 'Christmas_Invaders' || 'Space_Invaders' }}" ${{ matrix.file }}

      - name: Sauvegarder l'Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.file == 'christmasInvader.py' && 'Christmas_Build' || 'Space_Build' }}
          path: dist/*.exe

      - name: Créer/Modifier la Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}